config/routes.rb
Nodenock::Application.routes.draw do
  resources :calls do
    post "dial_out", :on => :member
  end

  resource :phone do
    match "verify(/:code)" => "phones#verify", :as => :verify
    get "resend_code"
  end

  resource :user do
    post "approve_friendship"
  end
  root :to => "users#show"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user

  before_create :generate_verification_code
  before_save :canonicalize_phone

  def verified?
    verification_code.nil?
  end

private

  # Thanks, stackoverflow
  # http://stackoverflow.com/questions/88311/
  def generate_verification_code
    o =  [('0'..'9'),('A'..'Z')].map{|i| i.to_a}.flatten;  
    self['verification_code']  =  (0..5).map{ o[rand(o.length)]  }.join;
  end

  def canonicalize_phone
    if(self['number'])
      self['number'].gsub!(/[- ()]/,'')
      if(! self['number'].starts_with? '+1')
        self['number'].gsub!(/^/,'+1')
      end
    end
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def create
    p = current_user.build_phone(params[:phone])
    p.save!
    result = send_verification(p.number,p.verification_code)
    redirect_to root_url, :notice => "We've sent a verification code to your phone."
  end

  def verify
    code = params[:code] ? params[:code].upcase : nil
    p = Phone.find_by_user_id_and_verification_code(current_user.id,code)
    if(p)
      p.verification_code = nil
      p.save!
      redirect_to root_url, :notice => "Your phone number has been verified!"
    else
      redirect_to root_url, :alert => "Sorry, that code was not valid."
    end
  end

  def resend_code
    notice = ""
    if(current_user)
      p = current_user.phone
      if(p && p.verification_code)
        send_verification(p.number, p.verification_code)
        notice = "We've sent a verification code to your phone."
      end
    end

    redirect_to root_url, :notice => notice
  end

  def destroy
    current_user.phone.destroy
    redirect_to root_url, :notice => "Phone deleted!"
  end

private

  def send_verification(number,code)
    msg = "Your Code is #{code}.\nOr visit #{verify_phone_url}/#{code}"
    Twilio::Sms.message(ENV['NODENOCK_PHONE'], number, msg)
  end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_edit.html.erb
<%= form_tag(phone_path, 'rel' => 'external') do %>
  <%= label_tag 'phone[number]', "Register your phone:"%>
  <%= text_field_tag 'phone[number]' %>
  <%= submit_tag "Confirm!" %>
<% end %>

app/views/phones/_show.html.erb
<div>Your Phone Number:</div>
<div align='center'><h3><%= current_user.phone.number %></h3></div>
<%= button_to "Change", phone_path, :method => :delete %>
<% if ! current_user.phone.verified? %>
  <%= form_tag(verify_phone_path, :method => :get, 'data-inline' => 'true') do %>
    <%= label_tag(:code, "Verification Code:") %>
    <%= text_field_tag(:code) %>
    <div data-role="controlgroup" data-type="horizontal" align="right">
      <%= link_to("Resend", resend_code_phone_path, 'data-role' => 'button') %>
      <%= submit_tag("Verify Me!", 'data-theme' => 'b') %>
    </div>
  <% end %>
  <script>
    $('input#resend_code').click(
      function(){
        var frm = $('input#resend_code')[0].form;
        form.action = "<%= resend_code_phone_path %>";
        form.method = "POST";
        form.submit();
        return true;
      }
    );
  </script>
<% end %>